---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: Applications/EXAMPLE/Modul/@tmpVersion@
  type: udm.DeploymentPackage
  deployables:
  - name: application-ear
    type: jee.Ear
    tags:
    - application
    scanPlaceholders: true
    textFileNamesRegex: .+\.(properties|xml)
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    file: !file "../application-ear-@version@.ear"
  - name: application-ejb
    type: file.Folder
    tags:
    - application
    fileEncodings:
      ".+\\.properties": ISO-8859-1
    targetPathShared: "true"
    createTargetPath: "true"
    file: !file "../application-ejb-@version@.jar"
